<?php

require_once 'src/loader.php';
require_once 'fixture/classes/Car.php';
require_once 'fixture/classes/Person.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-02 at 14:35:57.
 */
class LoaderTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Loader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Loader;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert ('Person') == new Person().
     *
     * @covers Loader::load
     */
    public function testLoad() {
        $this->assertEquals(
                new Person()
                , $this->object->load('Person')
        );
    }

    /**
     * Generated from @assert ('Car') == new Car().
     *
     * @covers Loader::load
     */
    public function testLoad2() {
        $this->assertEquals(
                new Car()
                , $this->object->load('Car')
        );
    }

    /**
     * Generated from @assert () throws InvalidArgumentException.
     *
     * @covers Loader::load
     * @expectedException InvalidArgumentException

     */
    public function testLoad3() {
        $this->object->load();
    }

    /**
     * Generated from @assert ('NoClass') throws UnexpectedValueException.
     *
     * @covers Loader::load
     * @expectedException UnexpectedValueException

     */
    public function testLoad4() {
        $this->object->load('NoClass');
    }

    /**
     * Generated from @assert ('Car') == new Car().
     *
     * @covers Loader::load
     */
    public function testLoad5() {
        $this->assertEquals(
                new Car()
                , $this->object->load('Car')
        );
    }

}
